// Harita editörü testi (ayrı bölüm ?editor=): kasaya bak + tıkla (seç) → sil / geri al / taşı / büyüt → kopyala → haritayı yeniden yükle (bellekte durur) → sıfırla → F5 (gider).
import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 } });
await ctx.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://127.0.0.1:5180' });
const page = await ctx.newPage();
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
const URL = 'http://127.0.0.1:5180/?editor=colgecidi&debug=1&nolock=1';
let fail = 0; const ok = (c, m) => { console.log((c ? 'OK   ' : 'HATA ') + m); if (!c) fail++; };
const boot = async () => { await page.goto(URL); await page.waitForFunction('window.__game && window.__game.running', null, { timeout: 120000 }); await page.waitForTimeout(1200);
  await page.evaluate(() => { const g = window.__game; const s = g.playerSoldier; s.fly = true; s.pos.set(-6.5, 1.3, -13.35); s.vel.set(0, 0, 0); s.yaw = -Math.PI / 2; s.pitch = -0.12; }); await page.waitForTimeout(500); };
await boot();
await page.evaluate(() => localStorage.removeItem('warbyte.harita-duzenleme.colgecidi'));
ok(await page.isVisible('#med'), 'editör bölümünde panel hazır açık');
await page.mouse.click(640, 360); await page.waitForTimeout(300);
const sel = await page.evaluate(() => window.__game.mapEditor.sel);
ok(!!sel, 'tıklanan nesne seçildi: ' + sel);
await page.screenshot({ path: 'screenshots/editor-select.png' });
const before = await page.evaluate((id) => { const g = window.__game; return g.world.colliders.filter((c) => c.oid === id).map((c) => [c.min.slice(), c.max.slice()]); }, sel);
await page.keyboard.press('ArrowUp'); await page.keyboard.press('PageUp'); await page.waitForTimeout(100);
const moved = await page.evaluate((id) => { const g = window.__game; return { cols: g.world.colliders.filter((c) => c.oid === id).map((c) => [c.min.slice(), c.max.slice()]), e: g.mapEditor.edits.get(id) }; }, sel);
ok(moved.e && Math.abs(moved.e.d[1] - 0.25) < 1e-6 && Math.hypot(moved.e.d[0], moved.e.d[2]) > 0.2, `taşındı (d=${JSON.stringify(moved.e?.d)})`);
ok(before.length === 0 || Math.abs(moved.cols[0][0][1] - before[0][0][1] - 0.25) < 1e-6, 'çarpışma kutusu da taşındı');
await page.keyboard.press('Equal'); await page.waitForTimeout(100);
ok(await page.evaluate((id) => Math.abs(window.__game.mapEditor.edits.get(id).s[0] - 1.1) < 1e-6, sel), 'büyütüldü (×1,1)');
await page.keyboard.press('Delete'); await page.waitForTimeout(150);
const del = await page.evaluate((id) => { const g = window.__game, ed = g.mapEditor; const r = ed.ranges.get(id)[0]; const P = r.mesh.geometry.attributes.position; return { y: P.getY(r.start), sel: ed.sel, del: !!ed.edits.get(id).del, hit: g.world.colliders.filter((c) => c.oid === id && c.min[0] < 1e5).length }; }, sel);
ok(del.del && del.y < -400 && del.hit === 0 && !del.sel, 'silindi (görsel + çarpışma)');
await page.keyboard.press('Backspace'); await page.waitForTimeout(150);
ok(await page.evaluate((id) => !window.__game.mapEditor.edits.get(id).del, sel), 'geri al: silme geri geldi');
await page.keyboard.press('End'); await page.waitForTimeout(300);
const txt = await page.evaluate(() => document.querySelector('#med textarea').value);
ok(txt.startsWith('HARİTA DÜZENLEMESİ colgecidi') && txt.includes(sel), 'düzenlemeler kopyalandı: ' + txt.split('\n')[1]?.slice(0, 120));
await page.keyboard.press('Home'); await page.waitForTimeout(200);
ok((await page.evaluate(() => document.querySelector('#med textarea').value)).startsWith(sel), 'kimlik kopyalandı');
await page.screenshot({ path: 'screenshots/editor-panel.png' });
// "Haritayı yeniden yükle" (aynı sayfa) → düzenleme bellekte durur, harita kurulurken uygulanır
const want = moved.e;
await page.evaluate(() => window.__game.mapEditor.cmd('reload'));
await page.waitForTimeout(500); await page.waitForFunction('window.__game && window.__game.running && window.__game.mapEditor', null, { timeout: 120000 }); await page.waitForTimeout(800);
const after = await page.evaluate((id) => { const g = window.__game; return { skipped: g.map.editSkipped, cols: g.world.colliders.filter((c) => c.oid === id).map((c) => [c.min.slice(), c.max.slice()]), n: g.mapEditor.list().length }; }, sel);
ok(after.n === 1, `yeniden yüklemede düzenleme duruyor (${after.n})`);
ok(before.length === 0 || Math.abs(after.cols[0][0][1] - (before[0][0][1] + 0.25)) < 0.2, 'yeniden yüklemede nesne taşınmış hâlde kuruldu');
await page.evaluate(() => { window.confirm = () => true; });
await page.evaluate(() => window.__game.mapEditor.cmd('reset'));
await page.waitForTimeout(500); await page.waitForFunction('window.__game && window.__game.running && window.__game.mapEditor', null, { timeout: 120000 });
ok(await page.evaluate(() => window.__game.mapEditor.list().length === 0), 'tümünü sıfırla temizledi');
// sayfa yenilenince (F5) düzenlemeler gider
await page.evaluate((id) => window.__game.mapEditor.move(id, [0, 1, 0]), sel); await boot();
ok(await page.evaluate(() => window.__game.mapEditor.list().length === 0 && !localStorage.getItem('warbyte.harita-duzenleme.colgecidi')), 'F5 sonrası düzenleme yok, tarayıcıya kaydedilmemiş');
console.log(fail ? `sonuç: HATA (${fail})` : 'sonuç: OK', 'sayfa hatası', errs.length, errs.slice(0, 3));
await browser.close();
