// Oyun içi Ayarlar / Kontroller paneli testi: duraklat → Ayarlar → kaydırıcı + düğme → Kontroller → tuş ata → kayıt ve oyuna yansıma.
import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
await page.goto('http://127.0.0.1:5180/?autostart=3v3&map=colgecidi&type=tdm&debug=1&nolock=1');
await page.waitForFunction('window.__game && window.__game.running', null, { timeout: 120000 });
await page.waitForTimeout(1500);
let fail = 0; const ok = (c, m) => { console.log((c ? 'OK   ' : 'HATA ') + m); if (!c) fail++; };
await page.evaluate(() => { const g = window.__game; g.time = 5; g.hud.setPaused(true); });
await page.click('#bSet'); await page.waitForTimeout(300);
ok(await page.isVisible('#igs'), 'Ayarlar paneli açıldı');
await page.screenshot({ path: 'screenshots/igs-settings.png' });
await page.$eval('#igs input[data-k=fov]', (el) => { el.value = 95; el.dispatchEvent(new Event('input', { bubbles: true })); });
await page.$eval('#igs input[data-k=sens]', (el) => { el.value = 0.004; el.dispatchEvent(new Event('input', { bubbles: true })); });
await page.$eval('#igs input[data-k=volume]', (el) => { el.value = 0.3; el.dispatchEvent(new Event('input', { bubbles: true })); });
await page.click('#igs [data-k=shadows]'); await page.click('#igs [data-k=quality][data-v="1"]');
const st = await page.evaluate(() => { const g = window.__game; return { fov: g.settings.fov, sens: g.settings.sens, vol: g.sfx.volume, sh: g.renderer.shadowMap.enabled, pr: g.renderer.getPixelRatio(), prefs: JSON.parse(localStorage.getItem(Object.keys(localStorage).find((k) => /pref|warbyte|bf/i.test(k)) || 'x') || '{}') }; });
ok(st.fov === 95 && st.sens === 0.004, `FOV / hassasiyet oyunda değişti (${st.fov}, ${st.sens})`);
ok(Math.abs(st.vol - 0.3) < 1e-6, `ana ses uygulandı (${st.vol})`);
ok(st.sh === false, 'gölgeler kapandı');
ok(st.pr <= 1, `çözünürlük düşük (${st.pr})`);
ok(st.prefs.fov === 95 && st.prefs.shadows === false && st.prefs.quality === 1, 'tercihlere kaydedildi');
await page.waitForTimeout(400);
const camFov = await page.evaluate(() => window.__game.camera.fov);
ok(Math.abs(camFov - 95) < 6, `kamera FOV yeni değere gidiyor (${camFov.toFixed(1)})`);
await page.click('#igs [data-tab=controls]'); await page.waitForTimeout(200);
await page.screenshot({ path: 'screenshots/igs-controls.png' });
await page.click('#igs [data-bind=reload][data-slot="0"]');
await page.keyboard.press('KeyP');
const kb = await page.evaluate(() => { const g = window.__game; return { reload: g.binds.codes('reload'), same: g.player.kb === g.binds, prefs: JSON.parse(localStorage.getItem(Object.keys(localStorage).find((k) => /pref|warbyte|bf/i.test(k)) || 'x') || '{}').keys }; });
ok(kb.reload[0] === 'KeyP' && kb.same, `R → P atandı ve oyuncu aynı atamayı kullanıyor (${kb.reload})`);
ok(kb.prefs && kb.prefs.reload && kb.prefs.reload[0] === 'KeyP', 'tuş ataması kaydedildi');
await page.click('#igs [data-k=leftHand][data-v="1"]');
ok(await page.evaluate(() => window.__game.leftHand === true), 'sol el anında uygulandı');
await page.click('#igs [data-k=kreset]');
ok(await page.evaluate(() => window.__game.binds.codes('reload')[0] === 'KeyR'), 'varsayılana dön çalıştı');
await page.keyboard.press('Escape'); await page.waitForTimeout(200);
ok(!(await page.isVisible('#igs')), 'Esc paneli kapattı');
ok(await page.isVisible('#pause'), 'duraklatma menüsü hâlâ açık');
console.log(fail ? `sonuç: HATA (${fail})` : 'sonuç: OK', 'sayfa hatası', errs.length, errs.slice(0, 2));
await browser.close();
